#!/bin/sh

set -e

echo "postrm $1 ..."

case "$1" in
    upgrade)
    ;;

    remove)
        ldconfig
    ;;

    purge)
        ldconfig
    ;;

    *)
        echo "unknown argument '$1'" >&2
        exit 0
    ;;
esac

exit 0
