#!/bin/sh

set -e

echo "preinst $1 ..."

UDEV_RULES_PATH=/etc/udev/rules.d
UDEV_RULES_FILE=80-drivers-SDK-2bdf.rules

case "$1" in
    install|upgrade)
        if [ -e $UDEV_RULES_PATH/$UDEV_RULES_FILE ]; then
            rm -f $UDEV_RULES_PATH/$UDEV_RULES_FILE
        fi
    ;;

    *)
        echo "unknown argument '$1'" >&2
        exit 0
    ;;
esac

exit 0

